
TN := ../bin/tn
# TNFLAGS := --dry-run

all:
	$(TN) $(TNFLAGS) ps
	$(TN) $(TNFLAGS) up
	$(TN) $(TNFLAGS) down
	$(TN) $(TNFLAGS) pull
	$(TN) $(TNFLAGS) exec
	$(TN) $(TNFLAGS) build
	$(TN) $(TNFLAGS) conf
	$(TN) $(TNFLAGS) reconf
	$(TN) $(TNFLAGS) reup
	$(TN) $(TNFLAGS) version
	$(TN) $(TNFLAGS) test
	$(TN) $(TNFLAGS) init
	$(TN) $(TNFLAGS) img
