
FROM slankdev/frr

# RUN sh -c 'echo nameserver 103.2.130.6 > /etc/resolv.conf' \
#  && apt update && apt install -y pppoeconf pppoe \
#  && sh -c 'echo nameserver 8.8.8.8 > /etc/resolv.conf'
# RUN echo slank

